### ISSUE TITLE
改一下吧 $a !== $b  不然  01  和 1 判定一样的了

### ISSUE THREAD

**Issue by ayhome** [top-think/think-orm#511] opened 2023-12-11 04:11 UTC
https://github.com/top-think/think-orm/blob/7b0b8ea6ca5e020217f6ba7ae34d547e148a675b/src/model/concern/Attribute.php#L352C13-L352C13

**Comment by big-dream** [comment] 2024-06-27 03:34
Duplicate of #299

**Closed as completed by big-dream** 2024-06-27 03:34 UTC
